-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

-- Create SEQUENCE for bid table
CREATE SEQUENCE bid_bid_id_seq;

-- Create SEQUENCE for car table
CREATE SEQUENCE car_car_id_seq;

-- Create SEQUENCE for advertisement table
CREATE SEQUENCE advertisement_ad_id_seq;

-- Create SEQUENCE for user_account table
CREATE SEQUENCE user_account_user_id_seq;

-- Create SEQUENCE for location table
CREATE SEQUENCE location_location_id_seq;

CREATE TABLE IF NOT EXISTS public.bid
(
    bid_id integer NOT NULL DEFAULT nextval('bid_bid_id_seq'::regclass),
    ad_id integer NOT NULL,
    bidder_id integer NOT NULL,
    date_bid date NOT NULL,
    bid_price integer NOT NULL,
    bid_status character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bid_pkey PRIMARY KEY (bid_id)
);

CREATE TABLE IF NOT EXISTS public.car
(
    car_id integer NOT NULL DEFAULT nextval('car_car_id_seq'::regclass),
    brand character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(255) COLLATE pg_catalog."default" NOT NULL,
    body_type character varying(25) COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    price integer NOT NULL,
    CONSTRAINT car_id PRIMARY KEY (car_id)
);

CREATE TABLE IF NOT EXISTS public.advertisement
(
    ad_id integer NOT NULL DEFAULT nextval('advertisement_ad_id_seq'::regclass),
    car_id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_post date,
    CONSTRAINT advertisement_pkey PRIMARY KEY (ad_id)
);

CREATE TABLE IF NOT EXISTS public.user_account
(
    user_id integer NOT NULL DEFAULT nextval('user_account_user_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    contact character varying(15) COLLATE pg_catalog."default" NOT NULL,
    location_id integer NOT NULL,
    CONSTRAINT user_account_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.location
(
    location_id integer NOT NULL DEFAULT nextval('location_location_id_seq'::regclass),
    city_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    CONSTRAINT location_pkey PRIMARY KEY (location_id)
);

ALTER TABLE IF EXISTS public.bid
    ADD CONSTRAINT ad_id FOREIGN KEY (ad_id)
    REFERENCES public.advertisement (ad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.advertisement
    ADD CONSTRAINT advertisement_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_account (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.advertisement
    ADD CONSTRAINT car_id FOREIGN KEY (car_id)
    REFERENCES public.car (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_account
    ADD CONSTRAINT location_id FOREIGN KEY (location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;